[[redirects]]
  from = "/js/*"
  to = "/assets/js/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/css/*"
  to = "/assets/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  status = 200
  force = true
  conditions = {Role = ["admin"]}
  
[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 401
  force = true