[[redirects]]
  from = "/js/*"
  to = "/assets/js/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/css/*"
  to = "/assets/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin"
  status = 301
  force = false
  conditions = {Role = ["admin"]}
  
[[redirects]]
  from = "/admin"
  to = "/"
  status = 301
  force = true