---
label: Base
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: datetime
  name: last_modified_at
  label: last_modified_at
- type: boolean
  name: comments
  label: comments
- type: textarea
  name: description
  label: description
- type: text
  name: categories
  label: categories
- type: list
  name: tags
  label: tags
- type: boolean
  name: math
  label: math
- type: boolean
  name: toc
  label: toc
- name: og_image
  type: file
  config:
    maxSize: 64
  label: Imagem
- name: ads
  type: boolean
  label: Ads
  default: true
pages:
- _posts/2021-10-02-site-rafael-dev-21-no-ar.md
- _posts/2021-10-05-jogo-da-cobrinha.md
- _posts/2021-10-06-jogo-cobra+refatorado.md
- _posts/2021-11-02-numeros.md
- _posts/2021-11-12-o-maravilhoso-mundo-dos-vetores.md
- _posts/2022-11-28-voltando-a-desenhar.md
- _posts/aprendendo-a-desenhar-parte-1-de-30.md
- index.md
